Repository fluxcd/terraform-provider-flux, pull requests merged in 2020-11, with the labels that each got.

#14 Update manifestgen to v0.2.1
  .gitignore
  Makefile
  go.mod
  go.sum
Labels: area/build

#15 Build binary and run tests in CI
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  main.go
  pkg/provider/data_install.go
  pkg/provider/data_sync.go
  pkg/provider/provider.go
Labels: area/build

#26 Add example to readme
  README.md
Labels: area/docs

#28 Add validation to log_level and url
  pkg/provider/data_install.go
  pkg/provider/data_install_test.go
  pkg/provider/data_sync.go
  pkg/provider/data_sync_test.go
Labels: enhancement
