Repository fluxcd/terraform-provider-flux, pull requests merged in 2024-05, with the labels that each got.

#679 Add `hostkey_algos` to the `git.ssh` schema
  docs/index.md
  internal/provider/provider.go
  internal/provider/resource_bootstrap_git_test.go
Labels: area/git

#680 Improve readiness diagnotics messages
  internal/provider/resource_bootstrap_git.go
Labels: area/kubernetes

#687 Add OpenTofu min supported version to readme
  README.md
Labels: area/docs

#688 Adding registry credential support to bootstrap resource.
  .golangci.yml
  docs/resources/bootstrap_git.md
  internal/provider/resource_bootstrap_git.go
Labels: enhancement
