Repository fluxcd/terraform-provider-flux, pull requests merged in 2024-04, with the labels that each got.

#631 ci: Fix GitHub e2e test
  .github/workflows/tests.yaml
Labels: area/testing

#632 Update dependencies to Go 1.22 and Kubernetes 1.29.3
  Makefile
  go.mod
  go.sum
Labels: dependencies

#636 Using the flux2-sync helm chart in the examples.
  .github/workflows/tests.yaml
  examples/helm-install/README.md
  examples/helm-install/main.tf
  examples/helm-install/providers.tf
Labels: area/testing

#638 fix: helm install e2e test
  .github/workflows/tests.yaml
Labels: area/testing

#640 fix: destroying helm e2e test.
  examples/helm-install/README.md
  examples/helm-install/main.tf
Labels: area/testing

#625 Adding more issue templates to maintain issue consistency.
  .github/ISSUE_TEMPLATE/00_bug_report.yaml
  .github/ISSUE_TEMPLATE/01_documentation.yaml
  .github/ISSUE_TEMPLATE/02_enhancement.yaml
  .github/ISSUE_TEMPLATE/03_repository.yaml
  .github/ISSUE_TEMPLATE/04_other.yaml
Labels: area/docs

#643 add: new example using personal access tokens.
  .github/workflows/tests.yaml
  README.md
  docs/index.md
  docs/resources/bootstrap_git.md
  examples/github-via-pat/README.md
  examples/github-via-pat/main.tf
  examples/github-via-pat/outputs.tf
  examples/github-via-pat/providers.tf
  examples/github-via-pat/variables.tf
  templates/index.md.tmpl
  templates/resources/bootstrap_git.md.tmpl
Labels: area/docs, area/testing

#644 Fix: GitHub via PAT e2e test.
  examples/github-via-pat/providers.tf
Labels: area/testing

#645 Fix(docs): Provider attribute descriptions.
  docs/index.md
  internal/provider/provider.go
Labels: area/docs

#647 feat(docs): Adding example of managing the flux ssh keypair in terraform.
  README.md
  docs/index.md
  examples/github-self-managed-ssh-keypair/README.md
  examples/github-self-managed-ssh-keypair/main.tf
  examples/github-self-managed-ssh-keypair/outputs.tf
  examples/github-self-managed-ssh-keypair/providers.tf
  examples/github-self-managed-ssh-keypair/variables.tf
  templates/index.md.tmpl
Labels: area/docs

#650 Adding optional git manifest delete.
  docs/resources/bootstrap_git.md
  internal/provider/resource_bootstrap_git.go
Labels: enhancement

#657 Provide an option not to delete the namespace flux is installed into.
  docs/resources/bootstrap_git.md
  internal/provider/resource_bootstrap_git.go
Labels: area/kubernetes

#658 Validate kubeconfig during provider configuration.
  docs/index.md
  internal/provider/provider.go
Labels: area/kubernetes

#664 Use embedded Flux manifests for air-gapped bootstrap
  .github/workflows/golangci-lint.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .gitignore
  Makefile
  docs/resources/bootstrap_git.md
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/resource_bootstrap_git.go
  internal/provider/resource_bootstrap_git_test.go
  main.go
Labels: enhancement

#666 Setting embedded_manifest to true and repo visibility to private.
  .github/workflows/pre-commit.yaml
  .pre-commit-config.yaml
  Makefile
  examples/github-self-managed-ssh-keypair/main.tf
  examples/github-via-pat/main.tf
  examples/github-via-ssh-with-gpg/main.tf
  examples/github-via-ssh/main.tf
  examples/github-with-customizations/main.tf
  examples/github-with-inline-customizations/main.tf
  examples/gitlab-via-ssh-with-gpg/main.tf
  examples/gitlab-via-ssh/main.tf
  examples/helm-install/README.md
  examples/helm-install/main.tf
  internal/provider/resource_bootstrap_git.go
  internal/provider/resource_bootstrap_git_test.go
Labels: area/docs, area/testing

#668 Update Terraform version in CI
  .github/workflows/tests.yaml
  Makefile
Labels: area/testing

#673 Update dependencies to Kubernetes 1.30
  go.mod
  go.sum
Labels: dependencies
